spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

queue:
    init-capacity: 10000

second-retry:
    enable: true

jwt:
    public_key: ${PUBLIC_KEY_LOCATION:classpath:keys/public-key.pem}
    issuer: http://otus-2023-12-architecture-auth
    audience: spaceship-client

